# Generated by Django 3.1.4 on 2021-01-12 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pauli', '0002_auto_20210112_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='user_ans',
            new_name='quiz_ans',
        ),
    ]
