# Generated by Django 3.1.4 on 2021-01-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pauli', '0003_auto_20210112_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('finished', 'finished'), ('pend', 'pending'), ('expired', 'expired')], default='pending', max_length=12),
        ),
    ]
