# Generated by Django 3.1.4 on 2021-01-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pauli', '0004_quiz_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='status',
            field=models.CharField(blank=True, choices=[('finished', 'finished'), ('pending', 'pending'), ('expired', 'expired')], default='pending', max_length=12, null=True),
        ),
    ]
